// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyyjukmesxgnrikayeyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5eWp1a21lc3hnbnJpa2F5ZXlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MDU4MDEsImV4cCI6MjA3MjQ4MTgwMX0.1_eT5C81o93mPa5596LuGCLwWS_LwqX-WCl0zKh9hEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});